import { useState } from "react";
import { Button } from "~/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "~/components/ui/card";
import { Wrench, Copy, Check, ExternalLink } from "lucide-react";

interface WorkflowSetupDialogProps {
  repoFullName: string;
}

const WORKFLOW_YAML = `name: AutoBuild Agent

on:
  repository_dispatch:
    types: [autobuild-ticket]

permissions:
  contents: write
  pull-requests: write

jobs:
  implement-ticket:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Claude Code
        run: npm install -g @anthropic-ai/claude-code

      - name: Create feature branch
        run: |
          git config user.name "AutoBuild Agent"
          git config user.email "autobuild@users.noreply.github.com"
          git checkout -b \${{ github.event.client_payload.branch_name }}

      - name: Run Claude Code Agent
        env:
          ANTHROPIC_API_KEY: \${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          claude -p "\${{ github.event.client_payload.prompt }}" \\
            --allowedTools "Edit,Write,Read,Glob,Grep,Bash" \\
            --output-format json \\
            --max-turns 50 \\
            > claude_output.json 2>&1 || true
          cat claude_output.json

      - name: Commit changes
        run: |
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
            echo "HAS_CHANGES=false" >> \$GITHUB_ENV
          else
            git commit -m "feat: \${{ github.event.client_payload.ticket_title }}"
            echo "HAS_CHANGES=true" >> \$GITHUB_ENV
          fi

      - name: Push branch
        if: env.HAS_CHANGES == 'true'
        run: git push origin \${{ github.event.client_payload.branch_name }}

      - name: Create Pull Request
        if: env.HAS_CHANGES == 'true'
        id: create-pr
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pr } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: \\\`[AutoBuild] \${{ github.event.client_payload.ticket_title }}\\\`,
              body: \\\`## AutoBuild Agent Implementation\\n\\n### Ticket\\n**\${{ github.event.client_payload.ticket_title }}**\\n\\n\${{ github.event.client_payload.ticket_description }}\\n\\n---\\n*This PR was automatically generated by AutoBuild Agent*\\\`,
              head: '\${{ github.event.client_payload.branch_name }}',
              base: '\${{ github.event.client_payload.base_branch }}'
            });
            console.log(\\\`Created PR #\\\${pr.number}: \\\${pr.html_url}\\\`);
            core.setOutput('pr_number', pr.number);
            core.setOutput('pr_url', pr.html_url);

      - name: Report results
        if: always()
        run: |
          if [ "\${{ env.HAS_CHANGES }}" == "true" ]; then
            STATUS="success"
            PR_URL="\${{ steps.create-pr.outputs.pr_url }}"
            PR_NUMBER="\${{ steps.create-pr.outputs.pr_number }}"
          else
            STATUS="no_changes"
            PR_URL=""
            PR_NUMBER=""
          fi
          curl -X POST "\${{ github.event.client_payload.callback_url }}" \\
            -H "Content-Type: application/json" \\
            -H "Authorization: Bearer \${{ github.event.client_payload.callback_secret }}" \\
            -d "{
              \\"ticket_id\\": \\"\${{ github.event.client_payload.ticket_id }}\\",
              \\"status\\": \\"\$STATUS\\",
              \\"pr_url\\": \\"\$PR_URL\\",
              \\"pr_number\\": \\"\$PR_NUMBER\\",
              \\"run_id\\": \\"\${{ github.run_id }}\\"
            }" || echo "Callback failed, but continuing..."`;

export function WorkflowSetupDialog({ repoFullName }: WorkflowSetupDialogProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [copiedYaml, setCopiedYaml] = useState(false);

  const copyYaml = async () => {
    await navigator.clipboard.writeText(WORKFLOW_YAML);
    setCopiedYaml(true);
    setTimeout(() => setCopiedYaml(false), 2000);
  };

  if (!isOpen) {
    return (
      <Button variant="outline" size="sm" onClick={() => setIsOpen(true)}>
        <Wrench className="w-4 h-4 mr-2" />
        Setup Agent
      </Button>
    );
  }

  return (
    <div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4">
      <Card className="w-full max-w-2xl max-h-[90vh] overflow-y-auto">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Wrench className="w-5 h-5" />
            Setup AutoBuild Agent
          </CardTitle>
          <CardDescription>
            Follow these steps to enable AI-powered ticket implementation for{" "}
            <span className="font-mono">{repoFullName}</span>
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* Step 1 */}
          <div className="space-y-2">
            <h3 className="font-semibold flex items-center gap-2">
              <span className="w-6 h-6 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-sm">
                1
              </span>
              Add the workflow file
            </h3>
            <p className="text-sm text-muted-foreground ml-8">
              Create a file at{" "}
              <code className="bg-muted px-1 rounded">
                .github/workflows/autobuild.yml
              </code>{" "}
              in your repository with the following content:
            </p>
            <div className="ml-8 relative">
              <pre className="bg-muted p-4 rounded-lg text-xs overflow-x-auto max-h-48">
                {WORKFLOW_YAML.slice(0, 500)}...
              </pre>
              <Button
                variant="secondary"
                size="sm"
                className="absolute top-2 right-2"
                onClick={copyYaml}
              >
                {copiedYaml ? (
                  <Check className="w-4 h-4" />
                ) : (
                  <Copy className="w-4 h-4" />
                )}
              </Button>
            </div>
          </div>

          {/* Step 2 */}
          <div className="space-y-2">
            <h3 className="font-semibold flex items-center gap-2">
              <span className="w-6 h-6 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-sm">
                2
              </span>
              Add your Anthropic API key
            </h3>
            <p className="text-sm text-muted-foreground ml-8">
              Go to your repository settings and add a secret named{" "}
              <code className="bg-muted px-1 rounded">ANTHROPIC_API_KEY</code>{" "}
              with your API key.
            </p>
            <div className="ml-8">
              <Button variant="outline" size="sm" asChild>
                <a
                  href={`https://github.com/${repoFullName}/settings/secrets/actions/new`}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <ExternalLink className="w-4 h-4 mr-2" />
                  Add Secret on GitHub
                </a>
              </Button>
            </div>
          </div>

          {/* Step 3 */}
          <div className="space-y-2">
            <h3 className="font-semibold flex items-center gap-2">
              <span className="w-6 h-6 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-sm">
                3
              </span>
              Start using AutoBuild
            </h3>
            <p className="text-sm text-muted-foreground ml-8">
              Once set up, drag any ticket to the "In Progress" column to
              trigger the AI agent. It will analyze your codebase, implement
              changes, and create a pull request automatically.
            </p>
          </div>

          <div className="flex justify-end gap-2 pt-4 border-t">
            <Button variant="ghost" onClick={() => setIsOpen(false)}>
              Close
            </Button>
            <Button asChild>
              <a
                href={`https://github.com/${repoFullName}/new/main?filename=.github/workflows/autobuild.yml`}
                target="_blank"
                rel="noopener noreferrer"
              >
                <ExternalLink className="w-4 h-4 mr-2" />
                Create File on GitHub
              </a>
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
